#!/bin/bash

set -e

echo "Updating System..."

sudo pacman --noconfirm -Syu
sudo pacman --noconfirm --needed -S git base-devel xorg-xinit xorg-server xorg-xsetroot

echo -e '1. nvidia\t2. xf86-video-amdgpu\t3. xf86-video-intel\t4. Skip'
read -r -p "Choose the driver(Default 1): " inp

case $inp in
	[1])
		vd='nvidia nvidia-utils'
		;;
	[2])
		vd='xf86-video-amdgpu'
		;;
	[3])
		vd='xf86-video-intel'
		;;
	[4])
		vd=""
		;;
	[*])
		vd='nvidia nvidia-utils'
		;;
esac

if ! [ -z "$vd" ]
then
	sudo pacman --needed -S $vd
fi

if pacman -Q | grep -i paru &> /dev/null
then
    helper="paru"
elif pacman -Q | grep -i yay &> /dev/null
then
    helper="yay"
else
    mkdir -p setWM/paru-aur
    git clone https://aur.archlinux.org/paru.git ./setWM/paru-aur
    cd ./setWM/paru-aur
    makepkg -si
    cd ../
    helper="paru"
fi

$helper --needed --noconfirm -S ttf-iosevka\
                 ttf-iosevka-term\
                 ttf-material-design-icons\
                 nerd-fonts-mononoki\
                 ttf-font-awesome\
                 nodejs-material-design-icons\
                 alacritty\
                 xmonad\
                 xmonad-contrib\
                 xorg-xsetroot\
                 polybar-git\
		 feh\
                 dmenu

mkdir tmp-clone
mkdir bak
git clone https://github.com/santhanuv17/dotfiles.git ./tmp-clone || { echo "Unable to clone"; exit;  }

fontSrc="./tmp-clone/fonts"
fontDist="/usr/local/share/fonts/ttf"

sudo mkdir -p "$fontDist/RadioUnchecked"
sudo cp "$fontSrc/RadioUnchecked/fonts/RadioUnchecked.ttf" "$fontDist/RadioUnchecked"

sudo mkdir -p "$fontDist/VolumeIcons"
sudo cp "$fontSrc/VolumeIcons/fonts/VolumeIcons.ttf" "$fontDist/VolumeIcons"

fc-cache

if [ -d $HOME/.config/wallpapers ]
then
	mv $HOME/.config/wallpapers bak/wallpapers-bak
fi
cp -r ./tmp-clone/wallpapers $HOME/.config/

if [ -d $HOME/.config/alacritty ]
then
    mv $HOME/.config/alacritty bak/alacritty-bak
fi
cp -r ./tmp-clone/terminals/alacritty $HOME/.config/

if [ -d $HOME/.config/polybar ]
then
    mv $HOME/.config/polybar bak/polybar-bak
fi
cp -r ./tmp-clone/bars/polybar-xmonad $HOME/.config/polybar

if [ -d $HOME/.xmonad ]
then
    mv $HOME/.xmonad bak/xmonad-bak
fi
mkdir -p $HOME/.xmonad
cp ./tmp-clone/wm/xmonad/xmonad.hs $HOME/.xmonad/xmonad.hs

if ! [ -f $HOME/.xinitrc ]
then
	touch $HOME/.xinitrc
fi

setCursorCmd="xsetroot -cursor_name left_ptr &"
if ! grep -Fxq "$setCursorCmd" "$HOME/.xinitrc"
then
	echo $setCursorCmd >> $HOME/.xinitrc
fi

execCmd="exec xmonad"
if ! grep -Fxq "$execCmd" "$HOME/.xinitrc"
then
	echo $execCmd >> $HOME/.xinitrc
fi

rm -rf ./tmp-clone
echo "All the existing configuarations files are moved to $PWD/bak"
echo "Run xmonad using startx command"
